# Generated by Django 4.2.10 on 2024-03-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_project", "0002_remove_book_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="favorite_genre",
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
