# Generated by Django 4.2.10 on 2024-03-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_project", "0003_member_favorite_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book", name="author", field=models.CharField(max_length=250),
        ),
    ]
