# Generated by Django 4.2.10 on 2024-03-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_project", "0004_alter_book_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="profile_picture",
            field=models.ImageField(default=0, upload_to=""),
            preserve_default=False,
        ),
    ]
