# Generated by Django 5.0.3 on 2024-03-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0005_member_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='favorite_genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
    ]
