# Generated by Django 5.0.2 on 2024-03-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0006_alter_member_favorite_genre_and_more'),
        ('django_project', '0006_book_genre_alter_member_favorite_genre_and_more'),
    ]

    operations = [
    ]
