# Generated by Django 4.2.11 on 2024-03-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_project", "0007_merge_20240314_2005"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="member",
            name="profile_picture",
            field=models.ImageField(
                upload_to="templates/library/media/profile_pictures/"
            ),
        ),
        migrations.DeleteModel(name="Favorite",),
    ]
