# Generated by Django 4.2.11 on 2024-03-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_project", "0009_favorite"),
    ]

    operations = [
        migrations.DeleteModel(name="Author",),
    ]
