# Generated by Django 5.0.3 on 2024-03-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0010_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
