# Generated by Django 4.2.11 on 2024-03-21 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_project", "0011_favorite_rating"),
    ]

    operations = [
        migrations.RemoveField(model_name="member", name="profile_picture",),
    ]
